### ISSUE TITLE
push brands down to subsidiaries

### ISSUE THREAD

**Issue by coyotemarin** [spendright/msd#15]
(Have to create the subsidiary table first, see #14.)

For example, Ben & Jerry's is a subsidiary of Unilever. Currently Ben & Jerry's is listed as both a brand of Unilever, and a company.

We could either list "Ben & Jerry's" as a brand of Ben & Jerry's, or (because it has the same name as a subsidiary) just treat it as an incorrect way of listing the company.

**Comment by davidmarin** [comment]
Also need to handle case where the "brand" is actually a subsidiary company. For example, I currently have `Plum Organics` listed as a brand of `Campbell's` and as its own company. Ideally, this shouldn't be a brand at all, just a subsidiary.

**Comment by coyotemarin** [comment]
Mapping brands to companies and vice versa is trickier than it's worth. In this case, "Ben & Jerry's" would be a brand of "Ben & Jerry's".
